version: '3.9'
services:

  zipkin-server:
    image: 'openzipkin/zipkin'
    ports:
      - '9411:9411'

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  config-server:
    image: sujithkumarmp/config-server.jar:1.1.0
    ports:
      - "8071:8071"   
    networks:
      default:
        aliases:
          - "config-server"      
 
  eureka-server:
    image: sujithkumarmp/eureka-server.jar:1.1.0
    ports:
      - "8070:8070"
    
    depends_on:
      - config-server
    networks:
      default:
        aliases:
          - "eureka-server"
          
  gateway-server:
    image: sujithkumarmp/gateway-server.jar:1.1.0
    ports:
      - "8072:8072"
    deploy:
      mode: replicated
      replicas: 2
    
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "gateway-server"
          
  oauth2-auth-server:
    image: sujithkumarmp/oauth2-auth-server.jar:1.0.0
    ports:
      - "8073:8073"
    depends_on:
      - config-server
    networks:
      default:
        aliases:
          - "oauth2-auth-server"
  bus-admin-service:
    image: sujithkumarmp/bus-admin-service.jar:1.0.0
    ports:
      - "8090:8090"
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "bus-admin-service"
  bus-inventory-service:
    image: sujithkumarmp/bus-inventory-service.jar:1.0.0
    ports:
      - "8091:8091"
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "bus-inventory-service"
  bus-user-service:
    image: sujithkumarmp/bus-user-service.jar:1.0.0
    ports:
      - "8092:8092"
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "bus-user-service"
  bus-payment-service:
    image: sujithkumarmp/bus-payment-service.jar:1.0.0
    ports:
      - "8093:8093"
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "bus-payment-service"
  bus-booking-service:
    image: sujithkumarmp/bus-booking-service.jar:1.0.0
    ports:
      - "8094:8094"
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "bus-booking-service"
