version: '3.9'
services:
  config-server:
    image: sujithkumarmp/config-server.jar:1.0.0
    ports:
      - "8071:8071"
    environment:
      CONFIGSERVER_PORT: "8071"
    networks:
      default:
        aliases:
          - "config-server"
    
 
  eureka-server:
    image: sujithkumarmp/eureka-server.jar:1.0.0
    ports:
      - "8070:8070"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://config-server"
      CONFIGSERVER_PORT: "8071"
      EUREKASERVER_PORT: "8070"
   
    depends_on:
      - config-server
    networks:
      default:
        aliases:
          - "eureka-server"
          
  gateway-server:
    image: sujithkumarmp/gateway-server.jar:1.0.0
    ports:
      - "8072:8072"
    deploy:
      mode: replicated
      replicas: 2
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-server"
      CONFIGSERVER_PORT: "8071"
      GATEWAYSERVER_PORT: "8072"
    
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "gateway-server"
          
  auth-service:
    image: sujithkumarmp/auth-service.jar:1.0.0
    ports:
      - "8090:8090"
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://config-server"
      CONFIGSERVER_PORT: "8071"
      GATEWAYSERVER_PORT: "8072"
      AUTHSERVICE_PORT: "8090"
    
    depends_on:
      - config-server
      - eureka-server
    networks:
      default:
        aliases:
          - "auth-service"
